### PR TITLE
nullable codecs fixes.

### PR DESCRIPTION
**Pull request by maciejbak85**
decodecs leaving as they were, just encoding

### CODE REVIEW

**Review by mcsherrylabs — COMMENTED** [review]
Did you forget about progress?
```
"state":{"status":"ready","progress":null}
```

**Comment by maciejbak85** [comment]
@mcsherrylabs yes forgot, pushed commit, I plan to test it locally with psg-services but want to finish this pretty print first

**Comment by maciejbak85** [comment]
@mcsherrylabs ok looks good:

`{
  "allOk": false,
  "lowBalancedWallets": [
    [
      "http://cardano-wallet-testnet3.iog.solutions:8090/v2/",
      [
        {
          "id": "9cfb32e1472ff0fbd97afb000f28bcab85957798",
          "address_pool_gap": 20,
          "balance": {
            "available": {
              "quantity": 0,
              "unit": "lovelace"
            },
            "reward": {
              "quantity": 0,
              "unit": "lovelace"
            },
            "total": {
              "quantity": 0,
              "unit": "lovelace"
            }
          },
          "delegation": {
            "active": {
              "status": "not_delegating"
            },
            "next": []
          },
          "name": "balance_w_1",
          "passphrase": {
            "last_updated_at": "2020-10-14T07:10:27.113563421Z"
          },
          "state": {
            "status": "ready"
          },
          "tip": {
            "epoch_number": 89,
            "slot_number": 325742,
            "height": {
              "quantity": 1928452,
              "unit": "block"
            },
            "absolute_slot_number": 8404142
          }
        }
      ]
    ]
  ],
  "errors": []
}
`

**Review by mcsherrylabs — APPROVED** [review]
Nice!

**Pull request merged**
